# Generated by Django 4.1.9 on 2023-05-14 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizData',
        ),
    ]
