# Generated by Django 4.1.9 on 2023-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_delete_quizdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('options', models.JSONField()),
                ('rightAnswer', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
            ],
        ),
    ]
