# Generated by Django 4.1.9 on 2023-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_quizdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
